config/routes.rb
PusherDemo::Application.routes.draw do

  resources :users
  resource :session
  resource :profile
  resources :messages do |messages|
    collection do
      get :sent
    end
  end

  match 'pusher/auth' => 'pusher#auth'

  root :to => 'welcome#index'

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :sender, :class_name => 'User'
  belongs_to :recipient, :class_name => 'User'

  validates :recipient, :presence => true
  validates :subject, :presence => true
  validates :body, :presence => true

  scope :by_user, lambda { |user| where(["sender_id = :user_id or recipient_id = :user_id", {:user_id => user.id}]) }
  scope :read, where("read_at is not null")
  scope :unread, where("read_at is null")

  def read!
    self.update_attribute(:read_at, Time.now)
  end

  def is_unread?
    read_at.blank?
  end

end

app/models/message_observer.rb
class MessageObserver < ActiveRecord::Observer
  include ActionView::Helpers::TextHelper

  def after_create(message)
    Pusher['broadcast'].trigger!('total_messages_changed', {:value => pluralize(Message.count, 'message', 'messages')})
    Pusher["private-user_#{message.recipient.id}"].trigger('unread_messages_changed', {:value => message.recipient.received_messages.unread.count})
    Pusher["private-user_#{message.recipient.id}"].trigger('new_message', {
      :sender => message.sender.username,
      :subject => message.subject,
      :excerpt => truncate(message.body, :length => 150),
      :url => "/messages/#{message.id}"
    })
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, :presence => true, :uniqueness => true
  validates :password, :presence => true, :on => :create

  has_many :sent_messages, :class_name => 'Message', :foreign_key => 'sender_id'
  has_many :received_messages, :class_name => 'Message', :foreign_key => 'recipient_id'

  def self.authenticate(username, password)
    find_by_username(username).try(:authenticate, password)
  end

  def to_s
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :unread_messages_count

  protected

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def unread_messages_count
    @unread_messages_count ||= current_user ? current_user.received_messages.unread.count : 0
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = current_user.received_messages.order('created_at desc')
  end

  def sent
    @messages = current_user.sent_messages.order('created_at desc')
  end

  def new
    @message = current_user.sent_messages.new(:recipient_id => params[:recipient_id])
    find_users
  end

  def create
    @message = current_user.sent_messages.new(params[:message])
    if @message.save
      redirect_to messages_path, :notice => "Your message was sent!"
    else
      find_users
      render :action => 'new'
    end
  end

  def show
    @message = Message.by_user(current_user).find(params[:id])
    if @message.recipient == current_user && @message.is_unread?
      @message.read!
    end
  end

  def destroy
    @message = Message.by_user(current_user).find(params[:id])
    @message.destroy
    redirect_to messages_url, :notice => "The message was deleted!"
  end

  protected

  def find_users
    @users = User.where("id <> ?", current_user.id)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_filter :find_user

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to :root, :notice => "Your profile was updated!"
    else
      render :action => 'edit'
    end
  end

  protected

  def find_user
    @user = current_user
  end

end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def auth
    if current_user && params[:channel_name] == "private-user_#{current_user.id}"
     render :json => Pusher[params[:channel_name]].authenticate(params[:socket_id])
    else
     render :text => "Not authorized", :status => '403'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:session][:username], params[:session][:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid username or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to :root, :notice => "Thank you for signing up!"
    else
      render :action => 'new'
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @total_messages = Message.count
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_flash_key_for(key)
    { :notice => "success", :alert => "error" }.fetch(key) { |key| key.to_s }
  end

  def messages_link(text, options = {})
    class_names = "unreadMessages label"
    class_names << " important" if unread_messages_count > 0
    link_to "#{text} <span class=\"#{class_names}\">#{unread_messages_count}</span>".html_safe,
            messages_path, options
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/pusher_helper.rb
module PusherHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def index

  end

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, msg| %>
  <div class="alert-message <%= bootstrap_flash_key_for(key) %> fade in" data-alert="alert">
    <a class="close" href="#">×</a>
    <p><%= msg %></p>
  </div>
<% end %>

app/views/layouts/_top_bar.html.erb
<%= link_to "MessageOmatic", root_path, :class => "brand" %>
<ul class="nav">
  <% unless current_user %>
    <li><%= link_to "Sign up", new_user_path %></li>
    <li><%= link_to "Sign in", new_session_path %></li>
  <% else %>
    <li><%= messages_link "Messages" %></li>
    <li><%= link_to "Edit profile", edit_profile_path %></li>
    <li><%= link_to "Sign out", session_path, :method => :delete %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript">
    window.pusher_key = '<%= ENV['PUSHER_KEY'] %>';
    <%= "window.user_id = #{current_user.id};" if current_user %>
  </script>
  <title>PusherDemo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "http://js.pusherapp.com/1.9/pusher.min.js", "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="topbar">
    <div class="fill">
      <div class="container">
        <%= render 'layouts/top_bar' %>
      </div>
    </div>
  </div>

  <div class="container">
    <%= render 'layouts/flash_messages' %>
  </div>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message, :wrapper => :inline do |f| %>
  <% if f.error_notification %>
    <div class="alert-message warning fade in" data-alert="alert">
      <a class="close" href="#">×</a>
      <p><%= f.error_notification %></p>
    </div>
  <% end %>
  <%= f.association :recipient, :input_html => {:class => "span12"}, :collection => @users %>
  <%= f.input :subject, :input_html => {:class => "span12"} %>
  <%= f.input :body, :input_html => {:class => "span12"} %>
  <div class="actions">
    <%= f.button :submit, :class => 'primary', :id => "commit" %>
  </div>
<% end %>

app/views/messages/_list.html.erb
<table class="bordered-table zebra-striped">
  <thead>
    <tr>
      <th></th>
      <th><%= context == 'received' ? 'From' : 'To' %></th>
      <th>Subject</th>
      <th>Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'list_message', :collection => @messages, :locals => {:context => context} %>
  </tbody>
</table>

app/views/messages/_list_message.html.erb
<tr>
  <td>
    <% if list_message.is_unread? %><span class="label success">Unread</span><% end %>
  </td>
  <td><%= context == 'received' ? list_message.sender.username : list_message.recipient.username %></td>
  <td><%= list_message.subject %></td>
  <td><%=l list_message.created_at, :format => :long %></td>
  <td>
    <%= link_to "Read", list_message %>
    <%= link_to "Delete", list_message, :method => :delete, :confirm => "Are you sure?" %>
  </td>
</tr>

app/views/messages/_menu.html.erb
<div class="well" style="padding: 14px 19px;">
  <%= link_to "Inbox", messages_path, :class => "btn" %>
  <%= link_to "Sent", sent_messages_path, :class => "btn" %>
  <%= link_to "Compose", new_message_path, :class => "btn primary" %>
  <% if @message.present? &&  @message.sender != current_user %>
    <%= link_to "Reply", new_message_path(:recipient_id => @message.sender_id), :class => "btn success" %>
    <%= link_to "Delete", @message, :method => :delete, :confirm => "Are you sure?", :class => "btn danger" %>
  <% end %>
</div>

app/views/messages/index.html.erb
<%= render 'menu' %>
<h1>Inbox</h1>
<%= render 'list', :context => 'received' %>

app/views/messages/new.html.erb
<%= render 'menu' %>
<h1>Compose message</h1>
<%= render 'form' %>

app/views/messages/sent.html.erb
<%= render 'menu' %>
<h1>Sent messages</h1>
<%= render 'list', :context => 'sent' %>

app/views/messages/show.html.erb
<%= render 'menu' %>
<h1>Message</h1>

<dl>
  <dt>From:</dt>
  <dd><%= @message.sender.username %></dd>
  <dt>To:</dt>
  <dd><%= @message.recipient.username %></dd>
  <dt>Date sent:</dt>
  <dd><%=l @message.created_at, :format => :long %></dd>
</dl>

<blockquote>
  <%= @message.body %>
</blockquote>

app/views/profiles/_form.html.erb
<%= simple_form_for @user, :url => profile_path, :wrapper => :inline do |f| %>
  <% if f.error_notification %>
    <div class="alert-message warning fade in" data-alert="alert">
      <a class="close" href="#">×</a>
      <p><%= f.error_notification %></p>
    </div>
  <% end %>
  <%= f.input :username %>
  <%= f.input :password, :hint => "Fill this out if you wish to change your password" %>
  <div class="actions">
    <%= f.button :submit, :class => 'primary', :id => "commit" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit profile</h1>
<%= render 'form' %>

app/views/users/_form.html.erb
<%= simple_form_for @user, :wrapper => :inline do |f| %>
  <% if f.error_notification %>
    <div class="alert-message warning fade in" data-alert="alert">
      <a class="close" href="#">×</a>
      <p><%= f.error_notification %></p>
    </div>
  <% end %>
  <%= f.input :username %>
  <%= f.input :password %>
  <div class="actions">
    <%= f.button :submit, :class => 'primary', :id => "commit" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form' %>

app/views/welcome/index.html.erb
<div class="hero-unit">
  <h1>Our users have sent <span id="total_messages"><%= pluralize(@total_messages, 'message', 'messages') %></span> to date.<br />Now go send more fucking messages!</h1>
  <p>
    Occaecat dolore shank, sint turkey bresaola drumstick proident tenderloin.
    Pancetta shoulder chuck rump laborum, exercitation filet mignon sirloin in
    nostrud jowl ball tip consequat jerky. Culpa jowl drumstick ex in hamburger.
    Drumstick pork belly ball tip, in cupidatat sed ham hock non aute quis shankle.
    Sed in flank officia irure, nisi sint est. Magna in pork aute. Magna brisket
    beef ribs fatback, consequat short ribs ground round.
  </p>
  <p>
    <% unless current_user %>
      <%= link_to "Sign up now »", new_user_path, :class => "btn primary large" %>
    <% else %>
      <%= link_to "Send a message »", new_message_path, :class => "btn success large" %>
    <% end %>
  </p>
</div>